// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/maxiloEmmmm/go-web/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
