// Code generated by entc, DO NOT EDIT.

package ent

import (
	"strconv"

	"github.com/google/uuid"
)

var apiClient *Client

func stringId(id string) string {
	return id
}

func intId(id string) int {
	val, _ := strconv.Atoi(id)
	return val
}

func int32Id(id string) int32 {
	return int32(int64Id(id))
}

func int64Id(id string) int64 {
	val, _ := strconv.ParseInt(id, 10, 64)
	return val
}

func uuidId(id string) uuid.UUID {
	u, _ := uuid.Parse(id)
	return u
}
